In [46]:
#df.to_csv("clean_laptop_data.csv")

In [47]:
import pandas as pd

In [48]:
df = pd.read_csv("laptopPrice.csv")

In [49]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [74]:
df.head()

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,1,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,34649
1,2,1,1,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,38999
2,2,1,1,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,39999
3,1,1,2,10th,8 GB,DDR4,512 GB,0 GB,2 GB,No warranty,No,69990
4,1,1,3,Not Available,4 GB,DDR4,0 GB,512 GB,0 GB,No warranty,No,26990

In [75]:
df.tail()

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
818,1,2,11,Not Available,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,135990
819,1,2,11,Not Available,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,144990
820,1,2,11,Not Available,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,149990
821,1,2,11,Not Available,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,142990
822,2,2,4,10th,8 GB,DDR4,512 GB,0 GB,0 GB,No warranty,No,57490

In [76]:
df.head(5)

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,1,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,34649
1,2,1,1,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,38999
2,2,1,1,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,39999
3,1,1,2,10th,8 GB,DDR4,512 GB,0 GB,2 GB,No warranty,No,69990
4,1,1,3,Not Available,4 GB,DDR4,0 GB,512 GB,0 GB,No warranty,No,26990

In [77]:
df.tail(4)

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
819,1,2,11,Not Available,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,144990
820,1,2,11,Not Available,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,149990
821,1,2,11,Not Available,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,142990
822,2,2,4,10th,8 GB,DDR4,512 GB,0 GB,0 GB,No warranty,No,57490

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 802 entries, 0 to 822
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   brand            802 non-null    int64
 1   processor_brand  802 non-null    int64
 2   processor_name   802 non-null    int64
 3   processor_gnrtn  802 non-null    object
 4   ram_gb           802 non-null    object
 5   ram_type         802 non-null    object
 6   ssd              802 non-null    object
 7   hdd              802 non-null    object
 8   graphic_card_gb  802 non-null    object
 9   warranty         802 non-null    object
 10  Touchscreen      802 non-null    object
 11  Price            802 non-null    int64
dtypes: int64(4), object(8)
memory usage: 81.5+ KB

In [79]:
df.describe()

            brand  processor_brand  processor_name          Price
count  802.000000       802.000000      802.000000     802.000000
mean     3.511222         1.283042        3.754364   76625.543641
std      2.282321         0.500623        2.959276   45232.984422
min      1.000000         1.000000        1.000000   16990.000000
25%      1.000000         1.000000        2.000000   45990.000000
50%      3.000000         1.000000        2.000000   63990.000000
75%      6.000000         2.000000        5.000000   89525.000000
max      8.000000         3.000000       11.000000  441990.000000

In [50]:
df.duplicated().sum()

np.int64(21)

In [51]:
df.drop_duplicates(inplace=True)

In [52]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
818    False
819    False
820    False
821    False
822    False
Length: 802, dtype: bool

In [53]:
df.duplicated().sum()

np.int64(0)

In [54]:
df.isnull()

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
819,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
820,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
821,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
822,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [55]:
df.dropna()

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [56]:
df.dtypes

brand                object
processor_brand      object
processor_name       object
processor_gnrtn      object
ram_gb               object
ram_type             object
ssd                  object
hdd                  object
os                   object
os_bit               object
graphic_card_gb      object
weight               object
warranty             object
Touchscreen          object
msoffice             object
Price                 int64
rating               object
Number of Ratings     int64
Number of Reviews     int64
dtype: object

In [57]:
df.drop(['os','os_bit','weight','msoffice','rating','Number of Ratings','Number of Reviews'],axis=1,inplace=True)

In [58]:
df["brand"].unique()

array(['ASUS', 'Lenovo', 'acer', 'Avita', 'HP', 'DELL', 'MSI', 'APPLE'],
      dtype=object)

In [59]:
brand_dict = {'ASUS' : 1,
               'Lenovo' : 2,
                 'acer':3, 
               'Avita':4, 
               'HP':5,
                 'DELL':6,
                   'MSI':7,
                     'APPLE':8}

In [60]:
df['brand']=df['brand'].map(brand_dict)

In [61]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,34649
1,2,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,38999
2,2,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,39999
3,1,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,2 GB,No warranty,No,69990
4,1,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,0 GB,No warranty,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,135990
819,1,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,144990
820,1,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,149990
821,1,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,142990
822,2,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,0 GB,No warranty,No,57490

In [62]:
df['processor_brand'].unique()

array(['Intel', 'AMD', 'M1'], dtype=object)

In [63]:
proc_brand_dict={'Intel':1, 'AMD':2, 'M1':3}

In [64]:
df['processor_brand']=df['processor_brand'].map(proc_brand_dict)

In [66]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,34649
1,2,1,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,38999
2,2,1,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,39999
3,1,1,Core i5,10th,8 GB,DDR4,512 GB,0 GB,2 GB,No warranty,No,69990
4,1,1,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,0 GB,No warranty,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,135990
819,1,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,144990
820,1,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,149990
821,1,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,142990
822,2,2,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,0 GB,No warranty,No,57490

In [65]:
df['processor_name'].unique()

array(['Core i3', 'Core i5', 'Celeron Dual', 'Ryzen 5', 'Core i7',
       'Core i9', 'M1', 'Pentium Quad', 'Ryzen 3', 'Ryzen 7', 'Ryzen 9'],
      dtype=object)

In [69]:
proc_name_dict={'Core i3':1, 'Core i5':2, 'Celeron Dual':3, 'Ryzen 5':4, 'Core i7':5,
       'Core i9':6, 'M1':7, 'Pentium Quad':8, 'Ryzen 3':9, 'Ryzen 7':10, 'Ryzen 9':11}

In [70]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,34649
1,2,1,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,38999
2,2,1,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,39999
3,1,1,Core i5,10th,8 GB,DDR4,512 GB,0 GB,2 GB,No warranty,No,69990
4,1,1,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,0 GB,No warranty,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,135990
819,1,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,144990
820,1,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,149990
821,1,2,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,142990
822,2,2,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,0 GB,No warranty,No,57490

In [71]:
df['processor_name']=df['processor_name'].map(proc_name_dict)

In [72]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,1,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,34649
1,2,1,1,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,38999
2,2,1,1,10th,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,39999
3,1,1,2,10th,8 GB,DDR4,512 GB,0 GB,2 GB,No warranty,No,69990
4,1,1,3,Not Available,4 GB,DDR4,0 GB,512 GB,0 GB,No warranty,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,11,Not Available,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,135990
819,1,2,11,Not Available,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,144990
820,1,2,11,Not Available,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,149990
821,1,2,11,Not Available,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,142990
822,2,2,4,10th,8 GB,DDR4,512 GB,0 GB,0 GB,No warranty,No,57490

In [73]:
df['processor_gnrtn'].unique()

array(['10th', 'Not Available', '11th', '7th', '8th', '9th', '4th',
       '12th'], dtype=object)

In [80]:
proc_gen_dict={'10th':1, 'Not Available':2, '11th':3, '7th':4, '8th':5, '9th':6, '4th':7,
       '12th':8}

In [81]:
df['processor_gnrtn'] = df['processor_gnrtn'].map(proc_gen_dict)

In [82]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,1,1,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,34649
1,2,1,1,1,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,38999
2,2,1,1,1,4 GB,DDR4,0 GB,1024 GB,0 GB,No warranty,No,39999
3,1,1,2,1,8 GB,DDR4,512 GB,0 GB,2 GB,No warranty,No,69990
4,1,1,3,2,4 GB,DDR4,0 GB,512 GB,0 GB,No warranty,No,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,11,2,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,135990
819,1,2,11,2,4 GB,DDR4,1024 GB,0 GB,0 GB,1 year,No,144990
820,1,2,11,2,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,149990
821,1,2,11,2,4 GB,DDR4,1024 GB,0 GB,4 GB,1 year,No,142990
822,2,2,4,1,8 GB,DDR4,512 GB,0 GB,0 GB,No warranty,No,57490

In [85]:
df.dtypes

brand               int64
processor_brand     int64
processor_name      int64
processor_gnrtn     int64
ram_gb             object
ram_type           object
ssd                object
hdd                object
graphic_card_gb    object
warranty           object
Touchscreen        object
Price               int64
dtype: object

In [86]:
df['ram_gb'].unique()

array(['4 GB', '8 GB', '16 GB', '32 GB'], dtype=object)

In [87]:
 ram_gb_dict = {'4 GB':4, '8 GB':8, '16 GB':16, '32 GB':32}

In [88]:
df['ram_gb'] = df['ram_gb'].map(ram_gb_dict)

In [89]:
df.dtypes

brand               int64
processor_brand     int64
processor_name      int64
processor_gnrtn     int64
ram_gb              int64
ram_type           object
ssd                object
hdd                object
graphic_card_gb    object
warranty           object
Touchscreen        object
Price               int64
dtype: object

In [90]:
df['ram_type'].unique()

array(['DDR4', 'LPDDR4', 'LPDDR4X', 'DDR5', 'DDR3', 'LPDDR3'],
      dtype=object)

In [91]:
ram_type_dict = {'DDR4':1, 'LPDDR4':2, 'LPDDR4X':3, 'DDR5':4, 'DDR3':5, 'LPDDR3':6}

In [92]:
df['ram_type'] = df['ram_type'].map(ram_type_dict)

In [93]:
df.dtypes

brand               int64
processor_brand     int64
processor_name      int64
processor_gnrtn     int64
ram_gb              int64
ram_type            int64
ssd                object
hdd                object
graphic_card_gb    object
warranty           object
Touchscreen        object
Price               int64
dtype: object

In [95]:
df ['ssd'].unique()

array(['0 GB', '512 GB', '256 GB', '128 GB', '1024 GB', '2048 GB',
       '3072 GB'], dtype=object)

In [99]:
ssd_dict =  {'0GB':0 , '512 GB':512, '256 GB':256, '128 GB':128, '1024 GB':1024, '2048 GB':1048,
       '3072 GB':3072}

In [102]:
df ['ssd'] = df ['ssd'].map(ssd_dict)

In [103]:
df.dtypes

brand                int64
processor_brand      int64
processor_name       int64
processor_gnrtn      int64
ram_gb               int64
ram_type             int64
ssd                float64
hdd                 object
graphic_card_gb     object
warranty            object
Touchscreen         object
Price                int64
dtype: object

In [107]:
df ['hdd'].unique()

array(['1024 GB', '0 GB', '512 GB', '2048 GB'], dtype=object)

In [108]:
hdd_dict = {'1024 GB':1024, '0 GB':0, '512 GB':512, '2048 GB':2048}

In [109]:
df['hdd'] = df['hdd'].map(hdd_dict)

In [110]:
df.dtypes

brand                int64
processor_brand      int64
processor_name       int64
processor_gnrtn      int64
ram_gb               int64
ram_type             int64
ssd                float64
hdd                  int64
graphic_card_gb     object
warranty            object
Touchscreen         object
Price                int64
dtype: object

In [111]:
df ['graphic_card_gb'].unique()

array(['0 GB', '2 GB', '4 GB', '6 GB', '8 GB'], dtype=object)

In [ ]:
phic_card_gb_dict gra= {'0 GB':0, '2 GB':2, '4 GB':4, '6 GB':6, '8 GB':8}

In [113]:
df ['graphic_card_gb'] = df ['graphic_card_gb'].map(graphic_card_gb_dict )

In [114]:
df.dtypes

brand                int64
processor_brand      int64
processor_name       int64
processor_gnrtn      int64
ram_gb               int64
ram_type             int64
ssd                float64
hdd                  int64
graphic_card_gb      int64
warranty            object
Touchscreen         object
Price                int64
dtype: object

In [115]:
df['warranty'].unique()

array(['No warranty', '1 year', '2 years', '3 years'], dtype=object)

In [116]:
warranty_dict = {'No warranty':0, '1 year':1, '2 years':2, '3 years':3}

In [117]:
df['warranty'] = df['warranty'].map(warranty_dict)

In [119]:
df.dtypes

brand                int64
processor_brand      int64
processor_name       int64
processor_gnrtn      int64
ram_gb               int64
ram_type             int64
ssd                float64
hdd                  int64
graphic_card_gb      int64
warranty             int64
Touchscreen         object
Price                int64
dtype: object

In [120]:
df['Touchscreen'].unique()

array(['No', 'Yes'], dtype=object)

In [121]:
Touchscreen_dict = {'No' : 0, 'Yes' : 1}

In [122]:
df['Touchscreen'] = df['Touchscreen'].map(Touchscreen_dict)

In [123]:
df.dtypes

brand                int64
processor_brand      int64
processor_name       int64
processor_gnrtn      int64
ram_gb               int64
ram_type             int64
ssd                float64
hdd                  int64
graphic_card_gb      int64
warranty             int64
Touchscreen          int64
Price                int64
dtype: object

In [124]:
df

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,graphic_card_gb,warranty,Touchscreen,Price
0,1,1,1,1,4,1,NaN,1024,0,0,0,34649
1,2,1,1,1,4,1,NaN,1024,0,0,0,38999
2,2,1,1,1,4,1,NaN,1024,0,0,0,39999
3,1,1,2,1,8,1,512.0,0,2,0,0,69990
4,1,1,3,2,4,1,NaN,512,0,0,0,26990
...,...,...,...,...,...,...,...,...,...,...,...,...
818,1,2,11,2,4,1,1024.0,0,0,1,0,135990
819,1,2,11,2,4,1,1024.0,0,0,1,0,144990
820,1,2,11,2,4,1,1024.0,0,4,1,0,149990
821,1,2,11,2,4,1,1024.0,0,4,1,0,142990
822,2,2,4,1,8,1,512.0,0,0,0,0,57490

In [125]:
df.dtypes

brand                int64
processor_brand      int64
processor_name       int64
processor_gnrtn      int64
ram_gb               int64
ram_type             int64
ssd                float64
hdd                  int64
graphic_card_gb      int64
warranty             int64
Touchscreen          int64
Price                int64
dtype: object